version: "3.9"
services:
  db:
    image: postgres:12
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgres/data
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "8080:8080"
    environment:
      HOST_BD: db
      USERNAME_DB: people
      PASSWORD_DB: 123456
    depends_on:
      - db

volumes:
  postgres_volume: